USE popidb;



UPDATE USER SET TRADE_NUM = (SELECT COUNT(*) FROM TRADE WHERE ID = SELLER);
UPDATE MARKET SET TRADE_NUM = (SELECT COUNT(*) FROM TRADE WHERE ID = MARKETID);

DROP PROCEDURE IF EXISTS ADD_TRADE;
DELIMITER $$
CREATE PROCEDURE ADD_TRADE(IN seller CHAR(8), 
	IN  item varchar(16), 
	IN	market int)
BEGIN
	INSERT INTO TRADE (SELLER, ITEM_NAME, MARKETID) values (seller, item, market);
	UPDATE USER SET TRADE_NUM = TRADE_NUM +1 WHERE ID = seller;
	UPDATE MARKET SET TRADE_NUM = TRADE_NUM +1 WHERE ID = market;
END $$

DELIMITER ;

CALL ADD_TRADE('a2','크롱',2);
CALL ADD_TRADE('a3','불국사',3);

SELECT * FROM USER;
SELECT * FROM TRADE;
SELECT * FROM MARKET;