USE popidb;

DROP PROCEDURE IF EXISTS SP_TEST1;
DELIMITER $$
CREATE PROCEDURE SP_TEST1(IN num INT,
	INOUT ret int)	
BEGIN
	DECLARE n INT;	
	SELECT * FROM USER WHERE TRADE_NUM >= num;
	SELECT * FROM MARKET WHERE TRADE_NUM >= num;
	SELECT COUNT(*) INTO n FROM USER WHERE TRADE_NUM > num;
	set ret = ret + n;		
END $$
DELIMITER ;

set @n = 10;
CALL SP_TEST1(2, @n);
SELECT @n;
